### ISSUE TITLE
Remove Amazon from available fulfillment services

### ISSUE THREAD

**Issue by csaunders** [Shopify/active_fulfillment#32]
The amazon fulfillment provider (Fulfillment Web Services) has been shutdown for more than a year. We should probably remove all that code and the tests since they just slow things down and add noise.

**Comment by wvanbergen** [comment]
Let's include this in #49. Is this `amazon`, or `amazon_mws`?

**Comment by csaunders** [comment]
`amazon` is the old FWS service

**Comment by wvanbergen** [comment]
OK, will remove.
