### ISSUE TITLE
Using Nokogiri

### ISSUE THREAD

**Issue by Tonkpils** [Shopify/active_fulfillment#59]
Current implementations of active_fulfillment services use REXML. Has there been any discussions to moving the implementations to use Nokogiri or something more performant?

**Comment by kevinhughes27** [comment]
Its been discussed, I think we would accept a PR with the change!

**Comment by Tonkpils** [comment]
Cool, I'll work on that then

**Comment by ddrmanxbxfr** [comment]
@Tonkpils Are you still working on it ?. I think I'll try to give a spin to it if you're not done yet.

Thanks!

**Comment by Tonkpils** [comment]
I started this effort but got swamped with work so didn't get to finish it. By all means have a it and if you have any questions let me know! :)

**Comment by ddrmanxbxfr** [comment]
@Tonkpils Converting it was pretty much straight foward. It should give a great performance boost :).

**Comment by ddrmanxbxfr** [comment]
@garethson @kevinhughes27 Now that everything is converted. Should we close this issue ?

Thanks!

**Comment by kevinhughes27** [comment]
yeah thanks so much!

**Comment by garethson** [comment]
:clap:
